name: Packer
on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1    
     
      - name: packer validate winsrv_2016.json
        uses: docker://hashicorp/packer:1.6.3
        with:
          args: validate winsrv_2016.json

      - name: packer build winsrv_2016.json
        uses: docker://hashicorp/packer:1.6.3
        with:
          args: build winsrv_2016.json
        env: 
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_SECRET: ${{ secrets.AZURE_SECRET }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
